name: Feature Pipeline - Hourly AQI Fetch

on: 
  schedule:
    - cron: '0 * * * *'  # cron syntax to fetch features every hour
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

          # Did not add these in "requirements.txt" (Linux-only dependencies for Hopsworks)
          pip install hops-deltalake
          pip install confluent-kafka

      - name: Run feature pipeline
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          cd feature_pipeline
          python pipeline.py

      - name: Export Hopsworks data
        run: |
          cd feature_pipeline
          python export_hopsworks.py

      - name: Commit updated dataset
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/aqi_features.csv

          git diff --cached --quiet || git commit -m "data: update AQI feature dataset"

          git push